# -*- coding: utf-8 -*-
"""Image Generation Using openai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozypC_28s8kZKfX3zEYOW-cGP_lIrLn-
"""

!pip install torch torchvision torchaudio transformers diffusers accelerate

import torch
from diffusers import StableDiffusionPipeline

# Check if CUDA (GPU) is available, otherwise use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load the Stable Diffusion model
model_id = "runwayml/stable-diffusion-v1-5"
pipe = StableDiffusionPipeline.from_pretrained(model_id)
pipe.to(device)  # Move model to GPU/CPU

# Define the prompt for image generation
prompt = " virat kholi image"
# Generate the image
image = pipe(prompt).images[0]

# Display the generated image
image.show()

# Save the image to a file
image.save("generated_image.png")

